# Generated by Django 5.1.3 on 2025-05-07 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratoryapp', '0006_alter_notification_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
    ]
