# Generated by Django 5.1.3 on 2025-05-07 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratoryapp', '0007_alter_notification_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
